[gsheets]

1. Your Service Account Email

This email MUST have Editor/Viewer access to your Google Sheet.

service_account_email = "orgaco@project-affb445a-acf9-4b9a-9bb.iam.gserviceaccount.com"

url = "1dL-nn9YirbzRRTxSQDREnO7xo5mdGKqZuzToqKAij5A"
